### PR TITLE
Move lowercase dirnames to uppercase dirnames for better use with com…

### PR DESCRIPTION
**Pull request by ghost**
Move lowercase dirnames to uppercase dirnames for better use with composer.

### CODE REVIEW

**Comment by swar8080** [comment]
Thanks for the commit.

Does the current naming style cause any issues for composer or is it just against the convention?

**Comment by ghost** [comment]
Yeah the autoload seems to not include the class files can't find the path.

**Comment by ghost** [comment]
I changed them to uppercase to match the use statements and they work.

**Comment by ghost** [comment]
https://stackoverflow.com/questions/31815777/psr-2-when-to-capitalize-directories

**Comment by ghost** [comment]
Autoloading with PSR 0 and 4. Dir names have to match it seems was my issue the use statements case didn't match the lower case

**Comment by swar8080** [comment]
Okay good to know, thanks,

**Pull request merged**
